### ISSUE TITLE
About "chordify" and "beat strength"

### ISSUE THREAD

**Issue by chomeyama** [sander-wood/deepchoir#2]
Hello. I've been working on harmonic generation recently, and I'm referring to your excellent work.
However, there are some unclear parts for me, and I would appreciate it if you could provide more details.
First, regarding Chordifying, could you provide specific code examples? I have already checked the music21 site, but I'm not sure about your preprocessing.
Next, about Labelling, where did you obtain the beat strength data? It is unavailable on https://github.com/czhuang/JSB-Chorales-dataset, and the original (?) site https://tardis.ed.ac.uk/~moray/harmony/ seems inaccessible.

**Comment by sander-wood** [comment]
Hi there,

Thank you for your interest in DeepChoir! Regarding your questions:

1. By using converter.parse(), the music file is read, and then chordify() is called on the score object to obtain the chords:
```python
# Read the music file
score = converter.parse(filename)
chords = score.chordify()
```

2. The beat strength is derived from the time signature of the music:
```python
def get_beat_label(n, ts, pre_ts_offset):
    label = 0
    medium = 0
    
    # Read time signature
    beatCount = ts.numerator
    beatDuration = 4 / ts.denominator

    if (ts.numerator % 3) == 0:
        medium = 3
    elif (ts.numerator % 2) == 0:
        medium = 2
        
    if (n.offset - pre_ts_offset) % (beatDuration) == 0:
        label += 1

        if medium != 0 and (n.offset - pre_ts_offset) % (beatDuration * medium) == 0:
            label += 1

            if medium != 0 and (n.offset - pre_ts_offset) % (beatDuration * beatCount) == 0:
                label += 1
    
    return label
```
I hope this clarifies things for you.

**Comment by chomeyama** [comment]
Thank you for the explanation! It has become clear now!
